import{a as v,i as g,S as w}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();async function p(o,e){const i="?key=42244518-9742bcd26a7acdceb08ce98f6",n="https://pixabay.com/api/",t=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=`${n}${i}${t}`,a={page:e,per_page:15};try{const c=(await v.get(r,{params:a})).data;if(c.hits&&c.hits.length>0)return c;C()}catch(m){console.error(m.message)}}const C=()=>g.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/src/img/error.svg",iconColor:"white",position:"topRight",maxWidth:"432px"}),I={imageElem:document.querySelector(".gallery")};function E(o){const e=o.map(({webformatURL:n,largeImageURL:t,tags:r,likes:a,views:m,comments:c,downloads:L})=>`<li class="gallery-item">
            <a href="${t}">
                <img src="${n}" alt="${r}""/>
                <div class="img-info">
                    <p class="info-item"><b>Likes:</b>${a}</p>
                    <p class="info-item"><b>Views:</b>${m}</p>
                    <p class="info-item"><b>Comments:</b>${c}</p>
                    <p class="info-item"><b>Downloads:</b>${L}</p>
                </div>
            </a>
        </li>`).join("");I.imageElem.insertAdjacentHTML("beforeend",e),new w(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}).refresh()}const u="image-tag",s={imgTagInput:document.querySelector("#search-img"),searchBtn:document.querySelector(".form"),imageElem:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-btn"),loader:document.querySelector(".backdrop")};let d,l,h;s.imgTagInput.addEventListener("input",$);s.searchBtn.addEventListener("submit",x);s.btnLoadMore.addEventListener("click",T);async function x(o){o.preventDefault(),d=s.imgTagInput.value.trim(),l=1,d===""?P():y();try{const e=await p(d,l);e.totalHits===0&&N(),h=Math.ceil(e.totalHits/15),s.imageElem.innerHTML="",f(e.hits)}catch(e){console.log(e.message),R()}localStorage.removeItem(u),S(),b(),s.searchBtn.reset()}async function T(){l+=1,y();const o=await p(d,l);f(o.hits),S(),b();const e=s.imageElem.firstElementChild.getBoundingClientRect().height;scrollBy({behavior:"smooth",top:e*2})}function O(o,e){const i=JSON.stringify(e);localStorage.setItem(o,i)}function $(){const e={tag:s.imgTagInput.value.trim()};O(u,e)}function z(o){const e=localStorage.getItem(o);try{return JSON.parse(e)}catch(i){return console.error("Error parsing JSON from localStorage:",i),{}}}function q(){const o=z(u)||{};s.imgTagInput.value=o.tag||""}q();function f(o){E(o)}function B(){s.btnLoadMore.classList.remove("hidden")}function M(){s.btnLoadMore.classList.add("hidden")}function y(){s.loader.classList.add("is-open")}function S(){s.loader.classList.remove("is-open")}function b(){l>=h?(M(),k()):B()}const P=()=>g.error({message:"Please enter a search tag",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/src/img/error.svg",iconColor:"white",position:"topRight"}),N=()=>g.error({message:"Sorry, no images found",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/src/img/error.svg",iconColor:"white",position:"topRight"}),R=()=>g.error({message:"Oops...",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/src/img/error.svg",iconColor:"white",position:"topRight"}),k=()=>g.info({message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",position:"bottomCenter"});
//# sourceMappingURL=commonHelpers.js.map
