import{a as w,i as d,S as v}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function p(o,t){const s="?key=42244518-9742bcd26a7acdceb08ce98f6",n="https://pixabay.com/api/",e=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=`${n}${s}${e}`,a={per_page:15,page:t};try{const c=(await w.get(r,{params:a})).data;if(c.hits&&c.hits.length>0)return c;C()}catch(g){console.error(g.message)}}const C=()=>d.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/img/error.svg",iconColor:"white",position:"topRight",maxWidth:"432px"}),E={imageElem:document.querySelector(".gallery")};function I(o){const t=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:g,comments:c,downloads:L})=>`<li class="gallery-item">
            <a href="${e}">
                <img src="${n}" alt="${r}""/>
                <div class="img-info">
                    <p class="info-item"><b>Likes:</b>${a}</p>
                    <p class="info-item"><b>Views:</b>${g}</p>
                    <p class="info-item"><b>Comments:</b>${c}</p>
                    <p class="info-item"><b>Downloads:</b>${L}</p>
                </div>
            </a>
        </li>`).join("");E.imageElem.insertAdjacentHTML("beforeend",t),new v(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}).refresh()}const u="image-tag",i={imgTagInput:document.querySelector("#search-img"),searchBtn:document.querySelector(".form"),imageElem:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-btn"),loader:document.querySelector(".backdrop")};let m,l,f;i.imgTagInput.addEventListener("input",$);i.searchBtn.addEventListener("submit",x);i.btnLoadMore.addEventListener("click",T);async function x(o){if(o.preventDefault(),m=i.imgTagInput.value.trim(),l=1,m==="")return B(),[];y();try{const t=await p(m,l);t.totalHits===0&&P(),f=Math.ceil(t.totalHits/15),i.imageElem.innerHTML="",h(t.hits)}catch{k()}localStorage.removeItem(u),b(),S(),i.searchBtn.reset()}async function T(){l+=1,y();const o=await p(m,l);h(o.hits),i.imageElem.firstElementChild.getBoundingClientRect().height,scrollBy({behavior:"smooth",top:10}),b(),S()}function $(){const t={tag:i.imgTagInput.value.trim()};saveToLS(u,t)}function O(o){const t=localStorage.getItem(o);try{return JSON.parse(t)}catch(s){return console.error("Error parsing JSON from localStorage:",s),{}}}function z(){const o=O(u)||{};i.imgTagInput.value=o.tag||""}z();function h(o){const t=I(o);i.imageElem.insertAdjacentHTML("beforeend",t)}function M(){i.btnLoadMore.classList.remove("hidden")}function q(){i.btnLoadMore.classList.add("hidden")}function y(){i.loader.classList.add("is-open")}function b(){i.loader.classList.remove("is-open")}function S(){l>=f?q():M()}const B=()=>d.error({message:"Please enter a search tag",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"}),P=()=>d.error({message:"Sorry, no images found",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"}),k=()=>d.error({message:"Oops...",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"});
//# sourceMappingURL=commonHelpers.js.map
