import{a as v,i as d,S as w}from"./assets/vendor-527658dd.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function p(o,e){const s="?key=42244518-9742bcd26a7acdceb08ce98f6",n="https://pixabay.com/api/",t=`&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=`${n}${s}${t}`,a={page:e,per_page:15};try{const c=(await v.get(r,{params:a})).data;if(c.hits&&c.hits.length>0)return c;C()}catch(g){console.error(g.message)}}const C=()=>d.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/img/error.svg",iconColor:"white",position:"topRight",maxWidth:"432px"}),E={imageElem:document.querySelector(".gallery")};function I(o){const e=o.map(({webformatURL:n,largeImageURL:t,tags:r,likes:a,views:g,comments:c,downloads:L})=>`<li class="gallery-item">
            <a href="${t}">
                <img src="${n}" alt="${r}""/>
                <div class="img-info">
                    <p class="info-item"><b>Likes:</b>${a}</p>
                    <p class="info-item"><b>Views:</b>${g}</p>
                    <p class="info-item"><b>Comments:</b>${c}</p>
                    <p class="info-item"><b>Downloads:</b>${L}</p>
                </div>
            </a>
        </li>`).join("");E.imageElem.insertAdjacentHTML("beforeend",e),new w(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}).refresh()}const u="image-tag",i={imgTagInput:document.querySelector("#search-img"),searchBtn:document.querySelector(".form"),imageElem:document.querySelector(".gallery"),btnLoadMore:document.querySelector(".load-btn"),loader:document.querySelector(".backdrop")};let m,l,f;i.imgTagInput.addEventListener("input",$);i.searchBtn.addEventListener("submit",x);i.btnLoadMore.addEventListener("click",T);async function x(o){o.preventDefault(),m=i.imgTagInput.value.trim(),l=1,m===""?P():y();try{const e=await p(m,l);e.totalHits===0&&N(),f=Math.ceil(e.totalHits/15),i.imageElem.innerHTML="",h(e.hits)}catch(e){console.log(e.message),k()}localStorage.removeItem(u),S(),b(),i.searchBtn.reset()}async function T(){l+=1,y();const o=await p(m,l);h(o.hits),i.imageElem.firstElementChild.getBoundingClientRect().height,scrollBy({behavior:"smooth",top:10}),S(),b()}function O(o,e){const s=JSON.stringify(e);localStorage.setItem(o,s)}function $(){const e={tag:i.imgTagInput.value.trim()};O(u,e)}function z(o){const e=localStorage.getItem(o);try{return JSON.parse(e)}catch(s){return console.error("Error parsing JSON from localStorage:",s),{}}}function M(){const o=z(u)||{};i.imgTagInput.value=o.tag||""}M();function h(o){const e=I(o);i.imageElem.insertAdjacentHTML("beforeend",e)}function q(){i.btnLoadMore.classList.remove("hidden")}function B(){i.btnLoadMore.classList.add("hidden")}function y(){i.loader.classList.add("is-open")}function S(){i.loader.classList.remove("is-open")}function b(){l>=f?B():q()}const P=()=>d.error({message:"Please enter a search tag",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"}),N=()=>d.error({message:"Sorry, no images found",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"}),k=()=>d.error({message:"Oops...",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"./img/error.svg",iconColor:"white",position:"topRight"});
//# sourceMappingURL=commonHelpers.js.map
